import 'translation_keys.dart' as translation;

class Ar {
  Map<String, String> get messages => {
        translation.title: 'العنوان',
        translation.subtitle: 'هذا هو العنوان الفرعي',
        translation.withParam: 'الترجمة مع المعلمة: مرحبا @param',
        'Report Page': 'صفحة التقرير',
        'select the issue that you want to report it !:':
            'اختر المشكلة التي تريد الإبلاغ عليها !:',
        'Camera Page': 'صفحة الكاميرا',
        'Take Picture': "إلتقاط صورة",
        'success': "تم الإنشاء بنجاح",
        'the report has been sent.': 'تم إرسال التقرير بنجاح.',
        'ok': 'موافق',
        'New Pothole Report': 'تقرير حفرة جديدة',
        'A new pothole report has been submitted': 'تم إرسال تقرير حفرة جديدة',
        'Reporting Page': 'صفحة التقرير',
        'Enter description': ' أدخل وصف للحفرةالتي تريد الإبلاغ عنها',
        'Save Picture': 'حفظ الصورة',
        'Fixed Potholes': "الحفر التي تم إصلاحها",
        'Unfixed Potholes': " الحفر التي لم يتم إصلاحها",
        'There is nothing to show here.': 'لا يوجد شيء لإظهاره هنا.',
        'Settings Page': "صفحة الإعدادات",
        'Username': "إسم المستخدم",
        'Full Name': "الاسم الكامل",
        'Email': "البريد الإلكتروني",
        'Sign Out': "تسجيل الخروج",
        'Switch to Arabic': 'تبديل اللغة إلى العربية',
        "Verify Email": "تأكيد البريد الإلكتروني",
        "A verfication email is sent": "تم إرسال بريد تأكيد بنجاح",
        "Resent Email": "إعادة إرسال بريد التأكيد",
        "cancell": "إلغاء",
        'Password Reset Email Sent': "تم إرسال بريد إعادة تعيين كلمة المرور",
        "Welcome Back! We Missed You!": "مرحبا بك",
        "email": "البريد الإلكتروني",
        "Password": "كلمة المرور",
        "Forgot Password?": "هل نسيت كلمة المرور؟",
        "Sign In": "تسجيل الدخول",
        "Or continue with": "أو المتابعة بي",
        "Not a member? ": "لم تقم بتسجيل من قبل",
        "Register now": "قم بتسجيل الأن",
        'Registration Successful. Please check your email for verification.':
            " تم التسجيل بنجاح. يرجى التحقق من بريدك الإلكتروني لتأكيد الحساب.",
        'OK': 'موافق',
        "Passwords don't match!": "  كلمة المرور غير متطابقة",
        'weak-password': " كلمة المرور قد تكون ضعيفة جدا",
        'The password provided is too weak.': " كلمة المرور قد تكون ضعيفة جدا",
        'email-already-in-use': " هذا البريد الإلكتروني مستخدم بالفعل",
        'The email address is already in use by another account.':
            " هذا البريد الإلكتروني مستخدم بالفعل بالمستخدم",
        'username-in-use': " اسم المستخدم مستخدم بالفعل",
        'The username already used.': " اسم المستخدم مستخدم بالفعل",
        'An error occurred. Please try again later.':
            " حدث خطأ. يرجى المحاولة لاحقا",
        "let's create an account for you!": "لنقم بإنشاء حساب لك!",
        "username": "إسم المستخدم",
        "full name": "الاسم الكامل",
        "confirm Password": "تأكيد كلمة المرور",
        "Sign Up": "إنشاء حساب",
        "Already Have An Account? ": " هل لديك حساب مسبقا؟",
        "Login now": " تسجيل الدخول الان",
        'Report Approved': 'تم الموافقة على البلاغ',
        'Your report has been approved by .': " تم الموافقة على بلاغك من قبل",
        'Report Refused': "تم إلغاء البلاغ",
        'Your report has been refused.': " تم إلغاء بلاغك",
        'Admin Page': "صفحة مدير البلاغ",
        'Error: User document or necessary fields not found.':
            " خطأ: ملف المستخدم أو الحقول اللازمة غير موجودة.",
        'Image': " صورة",
        'Report approved': " تم الموافقة على البلاغ",
        'Report deleted': "تم رفض البلاغ",
        "Admin Settings": " إعدادات مدير النظام",
        'User Report': " بلاغ المستخدم",
        'Report is Fixed': "البلاغات التي تم تصليحها",
        'Your report has been fixed by the government':" تم تصليح بلاغك من قبل الحكومة",
        'Analysing the reports' : "تحليل البلاغات",
        "Admin Analyse":"تحليل",
        'Analyse by Date and type and Street': "تحليل عن الطريق التاريخ و النوع و الشارع",
        'Average Fix Time Analysis':"تحليل متوسط وقت التصليح",
        'All':"الكل",
        'Average Fix Time':" متوسط وقت التصليح",
        'Calculate Average Fix Time':" حساب متوسط وقت التصليح",
        'Average Approval Time':" متوسط وقت الموافقة",
        'Calculate Average Approval Time':" حساب متوسط وقت الموافقة",
        'Average Fix Time After Approval':" متوسط وقت التصليح بعد الموافقة",
        'Calculate Average Fix Time After Approval':" حساب متوسط وقت التصليح بعد الموافقة",
         
         'Total Reports':' إجمالي البلاغات',
         'Select Type and Street':" اختر النوع و الشارع",
         'Calculate Total Reports':" حساب إجمالي البلاغات",
         'Clear Filters':" مسح الفلترات",
         'Other Issues':" مشاكل أخرى",
         'Streetlight':" مشاكل إنارة",
         'Pothole':" حفرة",
         'Your report has been delete it.':"بلاغك تم حذفه",
      };
}
