// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCFSNo5osicq7tZQvJLlkOfTa7mocI5U',
    appId: '1:115352858893:web:fc1f237af58a7dfa584044',
    messagingSenderId: '115352858893',
    projectId: 'astro44-3595c',
    authDomain: 'astro44-3595c.firebaseapp.com',
    storageBucket: 'astro44-3595c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZplZN_Dvpwiqos-W7Msd-YqNFQCIX42Q',
    appId: '1:115352858893:android:3a88281110774488584044',
    messagingSenderId: '115352858893',
    projectId: 'astro44-3595c',
    storageBucket: 'astro44-3595c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALz4CwoQdSGrwa3T8WRebf5EH35b8qo7A',
    appId: '1:115352858893:ios:48feb5dd02138f13584044',
    messagingSenderId: '115352858893',
    projectId: 'astro44-3595c',
    storageBucket: 'astro44-3595c.appspot.com',
    iosBundleId: 'com.example.astro44',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALz4CwoQdSGrwa3T8WRebf5EH35b8qo7A',
    appId: '1:115352858893:ios:d64e5c3d93d2f7e4584044',
    messagingSenderId: '115352858893',
    projectId: 'astro44-3595c',
    storageBucket: 'astro44-3595c.appspot.com',
    iosBundleId: 'com.example.astro44.RunnerTests',
  );
}
